name: Best Dinner Bot

on:
  schedule:
    - cron: "0,10,20,30,40,50 * * * *"
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: true
        default: "warning"
      tags:
        description: "Test scenario tags"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install bs4 requests pandas slack_sdk schedule datetime
      - run: python ./best_dinner_bot.py
        env: # Or as an environment variable
          SLACK_BOT_TOKEN: ${{ secrets.BEST_DINNER_SLACK_BOT_TOKEN }}
